services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-network

  phpmyadmin:
    image: phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: mariadb
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "8080:80"
    networks:
      - app-network

  # backend:
  #   build: ./backend
  #   container_name: symfony
  #   restart: unless-stopped
  #   environment:
  #     DATABASE_URL: ${DATABASE_URL}
  #   volumes:
  #     - ./backend:/var/www/html
  #   depends_on:
  #     - mariadb
  #   networks:
  #     - app-network

  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: unless-stopped
    ports:
      - "8001:80"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ./frontend/dist:/usr/share/nginx/html
    # depends_on:
      # - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
