vich_uploader:
    db_driver: orm

    mappings:
        movie_image:
            uri_prefix: /uploads/movies
            upload_destination: '%kernel.project_dir%/public/uploads/movies'
            
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true